services:
  main_service:
    container_name: "main_service"
    restart: unless-stopped
    build:
      context: ./../..
      dockerfile: base_service/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./../../base_service/src/config/.env:/app/src/config/.env:ro  # Монтирование .env файла
    networks:
      - socnet-network


networks:
  socnet-network:
    name: "socnet-network"
    external: true