services:
  postgresql: # запускаем контейнер постгрес
    container_name: "socnet-postgresql"
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: main, posts # бд которые будут созданы при инициализации
    ports:
      - "5432:5432" # порт для постгрес
    networks:
      - socnet-network
    volumes:
      - ./configs/create-multiple-db-with-users.sh:/docker-entrypoint-initdb.d/create-multiple-db-with-users.sh:ro
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  socnet-network:
    name: "socnet-network"